app/main/user/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/11/7 10:49
# @Author  : Sdlgyxl
# @Site    : 公司后台
# @File    : forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField, SubmitField, IntegerField, DateField, RadioField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms import ValidationError
from flask_pagedown.fields import PageDownField
from app.models.user import User, Dept
from app.models.commons import OfficeLocationChoices, JobStateChoices
from wtforms.fields.html5 import DateField
from flask_wtf.file import FileField, FileRequired, FileAllowed



class AddUserForm(FlaskForm):
    id = IntegerField("工号", render_kw = {"placeholder": "4位整数"})
    name = StringField('姓名', validators=[DataRequired(), Length(2, 4)], render_kw = {"placeholder": "2至4个汉字"})
    username = StringField('用户名',
                           validators=[
                               DataRequired(), Length(2, 20),
                               Regexp('^[A-Za-z][A-Za-z.]*$', 0, '用户名只能使用英文字母')],
                           render_kw = {"placeholder": "2至20位英文字母"})
    dept = SelectField('部门', coerce=int)
    superior = SelectField('上级', coerce=int)
    password = StringField("密码", validators=[DataRequired(), Length(8, 8), Regexp('^[1-9][0-9]{7}', 0, '必须是8位数字')], render_kw = {"placeholder": "8位数字"})
    mobile = StringField('手机号',
                         description='* 网站不会泄露您的手机号',
                         validators=[Regexp('(1[3-9][0-9]{9}){0,1}', 0, '手机号必须是11位数字')],
                         render_kw = {"placeholder": "请输入手机号"})
    email = StringField('邮箱', validators=[DataRequired(), Length(1, 64), Email(message=u"邮件格式有误")], render_kw={"placeholder": "E-mail: yourname@example.com"})
    birthday = DateField("出生日期", default='', format='%Y-%m-%d', validators=[DataRequired()])
    entrydate = DateField("入职日期", default='', format='%Y-%m-%d', validators=[DataRequired()])
    position = StringField('职务', validators=[DataRequired(), Length(2, 20)])
    office_location = SelectField("办公地点", coerce=int, choices = OfficeLocationChoices, validators=[DataRequired()])
    job_state = SelectField("工作状态", coerce=int, default=0, choices = JobStateChoices)
    profile = TextAreaField("个人简介", render_kw={"style": "height:120px"})
    can_login = RadioField("登录状态", coerce=int, choices = [(1, '允许登录'), (0, '禁止登陆')], default=1, render_kw={"class" : "form-inline"} )
    is_manager = RadioField("部门经理", coerce=int, choices = [(0, '职员'), (1, '经理')], default=0)
    photo = FileField("照片", validators=[FileAllowed(['jpg', 'png', 'gif'], '只能是.jpg .gif .png格式')])
    submit = SubmitField('保存')


    def __init__(self, *args, **kwargs):
        super(AddUserForm, self).__init__(*args, **kwargs)
        self.dept.choices = [(dept.id, dept.name)
                             for dept in Dept.query.order_by(Dept.superior, Dept.id).all()]
        self.superior.choices = [(0, '请选择')] + [(superior.id, str(superior.id) + '--' + superior.name)
                             for superior in User.query.filter_by(is_manager = 1).order_by(User.superior, User.id).all()]


    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经存在')

    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已经存在')

    def validate_mobile(self, field):
        if User.query.filter_by(mobile=field.data).first():
            raise ValidationError('手机号已经存在')


class EditUserForm(AddUserForm):
    password = None
    photo_clear = BooleanField('删除照片')
    submit = SubmitField('保存')

    def __init__(self, user, *args, **kwargs):
        super(EditUserForm, self).__init__(*args, **kwargs)
        self.user = user
        self.id.render_kw["readonly"] = "readonly"

    def validate_email(self, field):
        if field.data != self.user.email and \
                User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经存在')

    def validate_username(self, field):
        if field.data != self.user.username and \
                User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已经存在')

    def validate_mobile(self, field):
        if field.data != self.user.mobile and \
                User.query.filter_by(mobile=field.data).first():
            raise ValidationError('手机号已经存在')


class UserSearchForm(AddUserForm):
    q = StringField('搜索', validators=[DataRequired()])


class TestForm(FlaskForm):
    #name = StringField('姓名', validators=[DataRequired()])
    #dept = StringField('部门')
    photo = FileField("照片",
                     validators=[
                         # 文件必须选择;
                         FileRequired(),
                         #  指定文件上传的格式;
                         FileAllowed(['jpg', 'png', 'gif'], '只能是.jpg .gif .png格式')]
                      )
    ceshi = BooleanField('删除照片')
    submit = SubmitField('确定')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from .user import views as userview
userview.rp.register(bp)

from app.main import views

app/main/user/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/11/7 10:15
# @Author  : Sdlgyxl
# @Site    : 公司后台
# @File    : __init__.py.py

from flask import Blueprint

bp = Blueprint('user', __name__)

from . import views

app/main/user/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/11/7 10:16
# @Author  : Sdlgyxl
# @Site    : 公司后台
# @File    : views.py
from datetime import datetime
from flask import render_template, redirect, url_for, abort, flash, request, current_app, make_response, jsonify
from flask_login import current_user, login_required
from sqlalchemy import or_, and_
from .forms import EditUserForm, AddUserForm, TestForm, UserSearchForm
from app import db
from app.models.user import User, Dept
from app.models.commons import Privilege
from app.libs.redprint import Redprint

rp = Redprint('user')
from app.decorators import role_required


@rp.route("/")
@rp.route("/index/", methods=['GET', 'POST'])
@login_required
@role_required("用户列表")
def user_index(query=None):
    page = request.args.get('page', 1, type=int)
    query = request.args.get('q', '').strip()
    privi = current_user.get_privilege("用户列表")
    c = current_user.can_see_users(privi)
    if query:
        query = query.replace("'", "")
        c = or_(User.name.like('%{}%'.format(query)), User.username.like('%{}%'.format(query)))
        c = or_(User.position.like('%{}%'.format(query)), c)
        c = and_(current_user.can_see_users(privi), c)
    users = User.query.filter(c).order_by(User.id)
    pagination = users.paginate(page, current_app.config['POSTS_PER_PAGE'], False)

    # next_url = url_for('main.user_index', page=pagination.next_num, q=query) if pagination.has_next else None
    # prev_url = url_for('main.user_index', page=pagination.prev_num, q=query) if pagination.has_prev else None
    searchform = UserSearchForm()
    searchform.q.data = query
    return render_template('main/user/index.html', users=pagination.items, pagination=pagination,
                           title='用户列表', page=page, form=searchform, q=query)


@rp.route("/add", methods=['GET', 'POST'])
@login_required
@role_required("用户信息修改")
def user_add():
    form = AddUserForm()
    if form.validate_on_submit():
        user = User()
        filluser(user, form)
        return redirect(url_for('main.user_add'))
    return render_template('main/user/edit.html', form=form)


@rp.route("/edit/<id>", methods=['GET', 'POST'])
def user_edit(id):
    page = request.args.get('page', 1, type=int)
    user = User.query.get_or_404(id)
    form = EditUserForm(user=user)
    if form.validate_on_submit():
        filluser(user, form)
        return redirect(url_for('main.user_index', page=page))
    form.id.data = user.id
    form.name.data = user.name
    form.username.data = user.username
    form.dept.data = user.dept
    form.superior.data = user.superior
    form.mobile.data = user.mobile
    form.email.data = user.email
    form.birthday.data = user.birthday
    form.entrydate.data = user.entrydate
    form.position.data = user.position
    form.office_location.data = user.office_location
    form.job_state.data = user.job_state or 0
    form.profile.data = user.profile
    form.photo.data = user.photo
    form.can_login.data = user.can_login
    form.is_manager.data = user.is_manager

    return render_template('main/user/edit.html', form=form, user=user)


def filluser(user, form):
    photofile = None
    if form.photo.data:
        fileext = form.photo.data.filename.split('.')[-1]
        photofile = 'app/static/uploads/photo/' + str(datetime.now().timestamp()).replace('.', '') + '.' + fileext
        form.photo.data.save(photofile)
        photofile = photofile.replace('app/static/', '')
        user.photo = photofile
    if form.photo_clear.data:
        user.photo = None
    user.id = form.id.data
    user.name = form.name.data
    user.username = form.username.data
    user.dept_id = form.dept.data
    user.superior = form.superior.data if form.superior.data > 0 else None
    user.mobile = form.mobile.data
    user.email = form.email.data
    user.birthday = form.birthday.data
    user.entrydate = form.entrydate.data
    user.position = form.position.data
    user.office_location = form.office_location.data
    user.job_state = form.job_state.data
    user.profile = form.profile.data
    user.can_login = form.can_login.data
    user.is_manager = form.is_manager.data
    if not user.cr_date:
        user.cr_date = datetime.now()
    db.session.add(user)
    flash('The profile has been updated.')


@rp.route("/delete/<id>")
def user_delete(id):
    return "name = %s" % id


@rp.route("/updatepassword", methods=['GET', 'POST'])
def user_update_password():
    id = request.args.get('id', 1, type=int)
    password = request.args.get('password', 1, type=str)
    if current_user.cando("用户密码修改", id):
        user = User.query.get(id)
        user.password = password
        return jsonify({"state": "已经成功修改密码"})
    return jsonify({"state": "你没有修改该用户密码的权限"})


@rp.route("/deptmanagers", methods=['GET', 'POST'])
def dept_managers():
    deptid = request.args.get('deptid', 1, type=int)
    print('deptid', deptid)
    dept = Dept.query.get(deptid)
    str_sql = 'select id, name from users where is_manager = 1 and dept_id in(%s' % deptid
    if dept.superior:
        str_sql += "," + str(dept.superior)
    str_sql += ')'
    print('str_sql', str_sql)
    rst = db.session.execute(str_sql).fetchall()
    jsonlist = []
    for row in rst:
        jsonlist.append({'id': row[0], 'name': row[1]})
    return jsonify(jsonlist)


@rp.route("/test/", methods=['GET', 'POST'])
def user_test():
    form = TestForm()
    messages = []

    # 如果提交的数据验证通过，则返回True
    if form.validate_on_submit():
        '''
        #name = form.name.data
        #form.name.data = ''
        filename = form.photo.data.filename
        form.photo.data.save('uploads/' + filename)
        messages.append(filename)
        #messages.append(name)
        '''
        return str(form.ceshi.data)
        # return redirect(url_for('main.user_add'))
    return render_template('main/user/test.html', form=form, msg=messages)

app/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/11/6 16:37
# @Author  : Sdlgyxl
# @Site    : MicroBLOG
# @File    : views.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, jsonify, current_app
from flask_login import current_user, login_required
from app import db
from app.main import bp

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        #g.search_form = SearchForm()


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
    name = "world"
    if not current_user.is_anonymous:
        name = current_user.name
    return render_template('main/index.html', title="首页", name=name)

app/templates/main/user/edit.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
  <style>
    .control-label{white-space:nowrap}
    .radio{display: inline-block;}
  </style>
  <div class="page-header">
    <h1>用户修改</h1>
  </div>
  <div class="col-md-4">
    {{ wtf.quick_form(form, form_type="horizontal") }}
  </div>
{% endblock %}
{% block scripts %}
  {{ super() }}
  <script>
    $('#dept').on('change', function()
    {
      if($('#id').val() == 1001) return;
      selector = $("#superior");
      selector.find('option').remove();
      url = '/user/deptmanagers?deptid=' + $('#dept').val();
      fillSuperior(selector, url);
    });
    function fillSuperior(selector, url){
      $.ajax({
        type:'GET',
        url:url,
        success:function(data){
          for(var i=0;i<data.length;i++){
            selector.append('<option value="'+data[i].id+'">'+data[i].name+'</option>');
          }
        }
      });
    }
  </script>
{% endblock %}

app/templates/main/user/index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block app_content %}
  <div>
    <div class="col-md-4"><h1>Hi, {{ current_user.name }}</h1></div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <form class="form-search" style="margin-top: 20px" method="get" action="{{ url_for('main.user_index') }}">
        {{ form.q(size=20, class='form-control', placeholder=form.q.label.text) }}
      </form>
    </div>
  </div>
  <div style="clear:both"></div>
  <div class="table-responsive col-md-12">
  <div class="table-responsive">
  <table class="table table-hover table-striped table-condensed">
    <tr>
      <td width="4%"></td>
      <td width="4%">工号</td>
      <td width="6%">姓名</td>
      <td width="6%">部门</td>
      <td width="5%">上级</td>
      <td width="5%">用户名</td>
      <td width="10%">邮箱</td>
      <td width="8%">手机</td>
      <td width="4%">是否经理</td>
      <td width="3%">年龄</td>
      <td width="3%">工龄</td>
      <td width="5%">职务</td>
      <td width="4%">办公地</td>
      <td width="4%">职业状态</td>
      <td width="4%">允许登录</td>
      <td width="5%"></td>
      <td width="5%"></td>
    </tr>
    {% for user in users %}
      <tr>
        <td>
        {% if user.photo %}
          <img src="/static/{{ user.photo }}" style="width: 40px;height:40px;" />
        {% else %}
          <img src="{{ user.avatar(40) }}" style="width: 40px;height:40px;" />
        {%  endif %}
        </td>
        <td> {{ user.id }} </td>
        <td>
          <a href="{{ url_for('main.user_edit', id=user.id, page=request.args.get('page') or 1) }}">{{ user.name }}</a>
        </td>
        <td> {{ user.dept.name }} </td>
        <td> {{ user.superioruser.name }} </td>
        <td> {{ user.username }} </td>
        <td> {{ user.email }} </td>
        <td> {{ user.mobile }} </td>
        <td> {{ user.manager_state }} </td>
        <td> {{ user.age }} </td>
        <td> {{ user.service_length }} </td>
        <td> {{ user.position }} </td>
        <td> {{ user.office }} </td>
        <td> {{ user.jobstate }} </td>
        <td> {{ user.loginstate }} </td>
        <td>
          <a href="/user/edit/{{ user.id }}">编辑</a>
        </td>
        <td>
          <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal" onclick="values({{ user.id }})">
            修改密码
          </button>
        </td>
      </tr>
    {% endfor %}
  </table>
  </div>
  <nav aria-label="..." style="text-align: center">
    <div class="pagination">
      {{ macros.pagination_widget(pagination, '.user_index', q) }}
    </div>
  </nav>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">修改密码</h4>
        </div>
        <div class="modal-body">
          <input type="hidden" id="new_password_id" name="new_password_id">
          <input type="text" id="new_password" name="new_password" class="form-control" placeholder="请输入新密码" >
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          <button type="button" class="btn btn-primary" onclick="update_password();">提交更改</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal -->
  </div>
  <script>
  function update_password(){
    var data={
      'user_id':$('#new_password_id').val(),
      'new_password':$('#new_password').val()
    }
    $('#new_password').val('')
    $('#myModal').modal('hide');
    $.ajax({
      type:'GET',
      url:'/user/updatepassword?id=' + data.user_id + '&password=' + data.new_password,
      data:data,
      dataType:'json',
      success:function(data) {
        alert(data.state);
      }
    });
  }
  function values(ID){
    $('#new_password_id').val(ID);
  }
  </script>
{% endblock %}

app/templates/main/user/test.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
  <div class="page-header">
    <h1>test</h1>
  </div>
  <div class="col-md-12">
    <div class="col-md-4">
      {{ wtf.quick_form(form, form_type="horizontal") }}
    </div>
  </div>
  <div>
  {% for each in msg %}
  {{ each }}
  {%  endfor %}
  </div>
{% endblock %}