app/company/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018-11-15 13:26
# @Author  : Sdlgyxl
# @Site    : 公司后台
# @File    : forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField, SubmitField, IntegerField, DateField, RadioField
from wtforms.validators import DataRequired, Length, Email, Regexp
from wtforms import ValidationError
from flask_pagedown.fields import PageDownField
from app.models.user import User, Dept
from app.models.commons import *
from wtforms.fields.html5 import DateField
from flask_wtf.file import FileField, FileRequired, FileAllowed


class CompanyForm(FlaskForm):
    id = StringField("公司编号", render_kw = {"readonly": "readonly"})
    companyname = StringField('公司名称', validators=[DataRequired(), Length(6, 20)])
    hr_name = StringField('用户姓名', validators=[DataRequired(), Length(2, 4)])
    username = StringField('用户名',
                           validators=[
                               DataRequired(), Length(2, 20),
                               Regexp('^[A-Za-z][A-Za-z.]*$', 0, '用户名只能使用英文字母')],
                           render_kw = {"placeholder": "2至20位英文字母"})
    password = StringField("密码", validators=[DataRequired(), Length(6, 20)])
    email = StringField('邮箱', validators=[DataRequired(), Length(1, 64), Email(message=u"邮件格式有误")],
                        render_kw={"placeholder": "E-mail: yourname@example.com"})
    mobile = StringField('手机号',
                         description='* 网站不会泄露您的手机号',
                         validators=[Regexp('(1[3-9][0-9]{9}){0,1}', 0, '手机号必须是11位数字')],
                         render_kw = {"placeholder": "请输入手机号"})
    industry = SelectField("所属行业", coerce=int, default=0, choices=IndustryChoices)
    userlevel = SelectField("企业等级", coerce=int, default=0, choices=UserLevelChoices)
    city_id = SelectField("所在地区", coerce=int, default=0, choices=CityChoices)
    location = StringField('详细地址', validators=[DataRequired(), Length(6, 20)])
    homepage = StringField('公司主页', validators=[DataRequired(), Length(6, 20)])
    consultant = SelectField("招聘顾问", coerce=int, default=0)
    cr_date = StringField("注册时间", render_kw = {"readonly": "readonly"})
    profile = TextAreaField("企业简介", render_kw={"style": "height:120px"})
    submit = SubmitField('保存')


    def __init__(self, *args, **kwargs):
        super(CompanyForm, self).__init__(*args, **kwargs)
        self.consultant.choices = [(consultant.id, consultant.name)
                             for consultant in User.query.order_by(User.superior, User.id).all()]


class EditCompanyForm(CompanyForm):
    password = None

    def __init__(self, company, *args, **kwargs):
        super(EditCompanyForm, self).__init__(*args, **kwargs)
        self.company = company


class SearchForm(FlaskForm):
    q = StringField('搜索', validators=[DataRequired()])


class TestForm(FlaskForm):
    name = StringField('用户名', validators=[DataRequired()])
    submit = SubmitField('提交')

app/company/__init__.py
from flask import Blueprint

bp = Blueprint('company', __name__)

from app.company import views

app/company/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2018/11/6 16:37
# @Author  : Sdlgyxl
# @Site    : MicroBLOG
# @File    : views.py

from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, g, jsonify, current_app
from flask_login import current_user, login_required
from app import db
from app.company import bp
from app.decorators import role_required
from .forms import CompanyForm, EditCompanyForm, SearchForm, TestForm
from app.models.job import Company, Job
from app.models.commons import *


@bp.route("/")
@bp.route("/index/", methods=['GET', 'POST'])
@login_required
#@role_required("企业查询")
def index(query=None):
    page = request.args.get('page', 1, type=int)
    query = request.args.get('q', '').strip()
    privi = current_user.get_privilege("公司列表")
    if query:
        query = query.replace("'", "")
        c = (Company.name.like('%{}%'.format(query)), Company.profile.like('%{}%'.format(query)))
        companys = Company.query.filter(c).order_by(Company.id)
    companys = Company.query.order_by(Company.id)
    pagination = companys.paginate(page, current_app.config['POSTS_PER_PAGE'], False)

    # next_url = url_for('main.user_index', page=pagination.next_num, q=query) if pagination.has_next else None
    # prev_url = url_for('main.user_index', page=pagination.prev_num, q=query) if pagination.has_prev else None
    searchform = SearchForm()
    searchform.q.data = query
    #print(len(pagination.items))
    return render_template('company/index.html', companys=pagination.items, pagination=pagination,
                           title='企业列表', page=page, form=searchform, q=query)


@bp.route("/add", methods=['GET', 'POST'])
def add():
    form = CompanyForm()
    if form.validate_on_submit():
        company = Company()
        fill_company(company, form, 1)
        return redirect(url_for('company.add'))
    return render_template('company/company_edit.html', form=form)

#state 1 add; 2 edit
def fill_company(company, form, state):
    company.companyname = form.companyname.data
    company.hr_name = form.hr_name.data
    company.username = form.username.data
    company.email = form.email.data
    company.mobile = form.mobile.data
    company.profile = form.profile.data
    company.industry = form.industry.data
    company.userlevel = form.userlevel.data
    company.city_id = form.city_id.data
    company.location = form.location.data
    company.homepage = form.homepage.data
    if state == 1:
        company.state = 1
        company.reg_from = 1
        company.consultant = form.consultant.data
        company.cr_date = datetime.now()
        company.password = form.password.data
    db.session.add(company)


@bp.route("/edit/<id>", methods=['GET', 'POST'])
def edit(id):
    company = Company.query.get_or_404(id)
    form = EditCompanyForm(company=company)
    if form.validate_on_submit():
        fill_company(company, form, 2)
        return redirect(url_for('company.add'))
    form.id.data = company.id
    form.companyname.data = company.companyname
    form.hr_name.data = company.hr_name
    form.username.data = company.username
    form.email.data = company.email
    form.mobile.data = company.mobile
    form.profile.data = company.profile
    form.industry.data = company.industry
    form.userlevel.data = company.userlevel
    form.city_id.data = company.city_id
    form.location.data = company.location
    form.homepage.data = company.homepage
    form.consultant.data = company.consultant
    form.cr_date.data = company.cr_date
    return render_template('company/company_edit.html', form=form)


@bp.route("/updatepassword", methods=['GET', 'POST'])
def update_password():
    id = request.args.get('id', 1, type=int)
    password = request.args.get('password', 1, type=str)
    company = Company.query.get(id)
    company.password = password
    return jsonify({"state": "已经成功修改密码"})


@bp.route('/test', methods=['GET', 'POST'])
def test():
    # 创建表单对象
    form = TestForm()
    name = None
    # 表单校验
    if form.validate_on_submit():
        # 通过校验，则取出数据
        name = form.name.data
        form.name.data = ''
        # 渲染时分配到模板文件
    return render_template('/company/test.html', form=form, name=name)

app/templates/company/company_edit.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
  <style>
    .control-label{white-space:nowrap}
    .radio{display: inline-block;}
  </style>
  <div class="page-header">
    <h1>公司修改</h1>
  </div>
  <div class="col-md-4">
    {{ wtf.quick_form(form, form_type="horizontal") }}
  </div>
{% endblock %}

app/templates/company/company_edit_bak.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
  <style>
    .control-label{white-space:nowrap}
    .radio{display: inline-block;}
  </style>
  <div class="page-header">
    <h1>公司修改</h1>
  </div>
  <div class="col-md-4">
    {{ wtf.quick_form(form, form_type="horizontal") }}
  </div>
{% endblock %}

app/templates/company/index.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block app_content %}
  <div>
    <div class="col-md-4"><h1>Hi, {{ current_user.name }}</h1></div>
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <form class="form-search" style="margin-top: 20px" method="get" action="{{ url_for('main.user_index') }}">
        {{ form.q(size=20, class='form-control', placeholder=form.q.label.text) }}
      </form>
    </div>
  </div>
  <div style="clear:both"></div>
  <div class="table-responsive col-md-12">
  <div class="table-responsive">
  <table class="table table-hover table-striped table-condensed">
    <tr>
      <td width="4%">编号</td>
      <td width="10%">公司名称</td>
      <td width="6%">HR姓名</td>
      <td width="6%">用户名</td>
      <td width="5%">手机</td>
      <td width="8%">邮箱</td>
      <td width="8%">办公地点</td>
      <td width="8%">公司网址</td>
      <td width="5%">顾问</td>
      <td width="8%">注册时间</td>
      <td width="5%"></td>
      <td width="5%"></td>
    </tr>
    {% for company in companys %}
      <tr>       
        <td>{{ company.id }}</td>
        <td>{{ company.companyname }}</td>
        <td>{{ company.hr_name }}</td>
        <td>{{ company.username }}</td>
        <td>{{ company.mobile }}</td>
        <td>{{ company.email }}</td>
        <td>{{ company.location }}</td>
        <td>{{ company.homepage }}</td>
        <td>{{ company.consultant_info.name }}</td>
        <td>{{ company.cr_date }}</td>
        <td>
          <a href="/company/edit/{{ company.id }}">编辑</a>
        </td>
        <td>
          <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal" onclick="values({{ company.id }})">
            修改密码
          </button>
        </td>
      </tr>
    {% endfor %}
  </table>
  </div>
  <nav aria-label="..." style="text-align: center">
    <div class="pagination">
      {{ macros.pagination_widget(pagination, '.index', q) }}
    </div>
  </nav>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">修改密码</h4>
        </div>
        <div class="modal-body">
          <input type="hidden" id="companyid" name="companyid">
          <input type="text" id="password" name="password" class="form-control" placeholder="请输入新密码" >
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          <button type="button" class="btn btn-primary" onclick="update_password();">提交更改</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal -->
  </div>
  <script>
  function update_password(){
    var data={
      'companyid':$('#companyid').val(),
      'password':$('#password').val()
    }
    $('#password').val('')
    $('#myModal').modal('hide');
    $.ajax({
      type:'GET',
      url:'/company/updatepassword?id=' + data.companyid + '&password=' + data.password,
      data:data,
      dataType:'json',
      success:function(data) {
        alert(data.state);
      }
    });
  }
  function values(ID){
    $('#companyid').val(ID);
  }
  </script>
{% endblock %}

app/templates/company/test.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
  <style>
    .control-label{white-space:nowrap}
    .radio{display: inline-block;}
  </style>
  <div class="page-header">
    <h1>Hello {{ name }}</h1>
  </div>
  <div>
    {% if form.name.errors %}
      {{ form.name.errors[0] }}
    {% endif %}
  </div>
  <div class="col-md-4">
    <form action="{{ url_for('company.test') }}" method="post" >
      # {{form.hidden_tag()}}里面放的也就是csrf_token
      {{ form.csrf_token }}
      {{ form.name.label() }}{{ form.name(id='xx',class='yyy') }}
      {{ form.submit() }}
    </form>
  </div>
{% endblock %}